version: "3.8"
services:
  postgres:
    image: postgres:15
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
